### ISSUE TITLE
开启cors时报错

### ISSUE THREAD

**Issue by God-Chao** [vorbote/web-dev-suite#1]
yml的配置内容
```
cors:
      enabled: true
      allow-headers:
        - Content-Type
        - Authorization
        - token
        - x-token
      allow-origin:
        - '*'
      allow-methods:
        - GET
        - HEAD
        - POST
        - PUT
        - DELETE
        - TRACE
        - OPTIONS
        - PATCH
      allow-credentials: true
```
报错消息
java.lang.StringIndexOutOfBoundsException: start 0, end -1, length 0
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1810) ~[na:na]
	at java.base/java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:1070) ~[na:na]
	at java.base/java.lang.StringBuilder.substring(StringBuilder.java:91) ~[na:na]
	at cn.vorbote.web.filter.CorsFilter.fromArray(CorsFilter.java:130) ~[web-dev-suite-3.0.0.BETA.jar:na]
	at cn.vorbote.web.filter.CorsFilter.doFilter(CorsFilter.java:153) ~[web-dev-suite-3.0.0.BETA.jar:na]

**Comment by theodorehills** [comment]
稍后排查一下这个问题

**Comment by God-Chao** [comment]
您好，邮件我已收到，辛苦您了！我会尽快阅读并且给您回复。如有急事，请直接致电：15207340242

**Comment by theodorehills** [comment]
问题已修复，请克隆本仓库并在控制台运行指令 `mvn clean install -P snapshot` 即可
